// GENERATED by runtime/frames/gen.mjs from frames.json -- do not edit.
// Payload words are the fields in order; a name[] field is a trailing run whose count is the field before it.
export const FRAME = {
  MATCH_START: 1,
  ROUND_START: 2,
  FALL: 3,
  SPAWN: 4,
  TIMER: 5,
  TICK_END: 6,
  STREAMS: 16,
  VERDICT: 18,
} as const;
export type FrameName = keyof typeof FRAME;
export const FRAME_NAME: Record<number, FrameName> = Object.fromEntries(Object.entries(FRAME).map(([k, v]) => [v, k])) as Record<number, FrameName>;

export interface MATCH_STARTFrame { seed: number; mode: number; lives: number; rounds: number; kocredit: number; spots: number; nplayers: number; team: Int32Array }
export function packMATCH_START(seed: number, mode: number, lives: number, rounds: number, kocredit: number, spots: number, nplayers: number, team: ArrayLike<number>): Int32Array {
  return Int32Array.from([seed | 0, mode | 0, lives | 0, rounds | 0, kocredit | 0, spots | 0, nplayers | 0, ...Array.from(team, (v) => v | 0)]);
}
export function readMATCH_START(p: Int32Array): MATCH_STARTFrame {
  return { seed: p[0], mode: p[1], lives: p[2], rounds: p[3], kocredit: p[4], spots: p[5], nplayers: p[6], team: p.subarray(7) };
}

export interface ROUND_STARTFrame { round: number }
export function packROUND_START(round: number): Int32Array {
  return Int32Array.from([round | 0]);
}
export function readROUND_START(p: Int32Array): ROUND_STARTFrame {
  return { round: p[0] };
}

export interface FALLFrame { tick: number; victim: number; lastHitBy: number; lastHitTick: number }
export function packFALL(tick: number, victim: number, lastHitBy: number, lastHitTick: number): Int32Array {
  return Int32Array.from([tick | 0, victim | 0, lastHitBy | 0, lastHitTick | 0]);
}
export function readFALL(p: Int32Array): FALLFrame {
  return { tick: p[0], victim: p[1], lastHitBy: p[2], lastHitTick: p[3] };
}

export interface SPAWNFrame { tick: number; player: number }
export function packSPAWN(tick: number, player: number): Int32Array {
  return Int32Array.from([tick | 0, player | 0]);
}
export function readSPAWN(p: Int32Array): SPAWNFrame {
  return { tick: p[0], player: p[1] };
}

export interface TIMERFrame { tick: number }
export function packTIMER(tick: number): Int32Array {
  return Int32Array.from([tick | 0]);
}
export function readTIMER(p: Int32Array): TIMERFrame {
  return { tick: p[0] };
}

export interface TICK_ENDFrame { tick: number }
export function packTICK_END(tick: number): Int32Array {
  return Int32Array.from([tick | 0]);
}
export function readTICK_END(p: Int32Array): TICK_ENDFrame {
  return { tick: p[0] };
}

export interface STREAMSFrame { s0: number; s1: number; s2: number }
export function packSTREAMS(s0: number, s1: number, s2: number): Int32Array {
  return Int32Array.from([s0 | 0, s1 | 0, s2 | 0]);
}
export function readSTREAMS(p: Int32Array): STREAMSFrame {
  return { s0: p[0], s1: p[1], s2: p[2] };
}

export interface VERDICTFrame { round: number; result: number; winner: number; sudden: number; matchover: number; creditVictim: number; creditAttacker: number; wins0: number; wins1: number; wins2: number; wins3: number; wins4: number; wins5: number; wins6: number; wins7: number; nplayers: number; players: Int32Array }
export function packVERDICT(round: number, result: number, winner: number, sudden: number, matchover: number, creditVictim: number, creditAttacker: number, wins0: number, wins1: number, wins2: number, wins3: number, wins4: number, wins5: number, wins6: number, wins7: number, nplayers: number, players: ArrayLike<number>): Int32Array {
  return Int32Array.from([round | 0, result | 0, winner | 0, sudden | 0, matchover | 0, creditVictim | 0, creditAttacker | 0, wins0 | 0, wins1 | 0, wins2 | 0, wins3 | 0, wins4 | 0, wins5 | 0, wins6 | 0, wins7 | 0, nplayers | 0, ...Array.from(players, (v) => v | 0)]);
}
export function readVERDICT(p: Int32Array): VERDICTFrame {
  return { round: p[0], result: p[1], winner: p[2], sudden: p[3], matchover: p[4], creditVictim: p[5], creditAttacker: p[6], wins0: p[7], wins1: p[8], wins2: p[9], wins3: p[10], wins4: p[11], wins5: p[12], wins6: p[13], wins7: p[14], nplayers: p[15], players: p.subarray(16) };
}

