// MB_OUTPOST — recovered from the 2007 HL2 mod BSP.
//
// GENERATED by tools/bsp/bsp2mapdef.mjs from maps/mb_outpost.bsp; see
// docs/ASSET-RECOVERY.md. Geometry is the brush AABBs, so this is the massing of
// the original, not its detail. Hand-edit freely — this file is checked in and
// regenerating it is a deliberate act, not part of the build.
//
// Original scripting (point_template crate spawners, logic_case/logic_timer drop
// director) is intentionally NOT ported; the sim owns that behaviour.
//
// 36 of 81 brushes were not axis-aligned and have been
// squared off to their bounding box (marked `approx` in the source data).
import type { MapDef } from './types.ts';

export const mboutpost: MapDef = {
  id: 'mb_outpost',
  name: 'MB OUTPOST',
  platforms: [
    { x: 17.7, y: 12.14, z: -0.24, w: 4.06, h: 0.81, d: 4.88 },
    { x: 19.33, y: 1.17, z: 1.79, w: 0.81, h: 21.13, d: 0.81 },
    { x: 19.33, y: 8.69, z: -0.24, w: 0.81, h: 6.1, d: 3.25 }, // approx (angled brush)
    { x: 19.33, y: 1.17, z: -2.27, w: 0.81, h: 21.13, d: 0.81 },
    { x: 19.33, y: 2.59, z: -0.24, w: 0.81, h: 6.1, d: 3.25 }, // approx (angled brush)
    { x: 17.7, y: -4.93, z: -0.24, w: 4.06, h: 8.94, d: 3.25 },
    { x: 16.08, y: 1.17, z: 1.79, w: 0.81, h: 21.13, d: 0.81 },
    { x: 16.08, y: 2.59, z: -0.24, w: 0.81, h: 6.1, d: 3.25 }, // approx (angled brush)
    { x: 17.7, y: 3, z: 0.58, w: 0.41, h: 6.91, d: 0.41 },
    { x: 17.7, y: 8.48, z: 1.79, w: 2.44, h: 6.1, d: 0.81 }, // approx (angled brush)
    { x: 16.08, y: 1.17, z: -2.27, w: 0.81, h: 21.13, d: 0.81 },
    { x: 17.7, y: 8.69, z: -2.27, w: 2.44, h: 6.1, d: 0.81 }, // approx (angled brush)
    { x: 17.7, y: 2.59, z: -2.27, w: 2.44, h: 6.1, d: 0.81 }, // approx (angled brush)
    { x: 17.7, y: 3, z: -1.05, w: 0.41, h: 6.91, d: 0.41 },
    { x: 17.7, y: 6.65, z: -0.24, w: 1.63, h: 0.41, d: 2.44 },
    { x: 17.7, y: 6.65, z: -1.66, w: 2.44, h: 0.41, d: 0.41 }, // approx (angled brush)
    { x: 18.72, y: 6.65, z: -0.24, w: 0.41, h: 0.41, d: 3.25 }, // approx (angled brush)
    { x: 16.68, y: 6.65, z: -0.24, w: 0.41, h: 0.41, d: 3.25 }, // approx (angled brush)
    { x: 17.7, y: 6.65, z: 1.19, w: 2.44, h: 0.41, d: 0.41 }, // approx (angled brush)
    { x: 16.08, y: 6.45, z: -0.24, w: 0.81, h: 0.81, d: 3.25 },
    { x: 17.7, y: -4.93, z: -2.27, w: 2.44, h: 8.94, d: 0.81 },
    { x: 25.42, y: 1.98, z: 2.2, w: 2.16, h: 1.63, d: 2.16 }, // approx (angled brush)
    { x: 25.42, y: 0.36, z: 2.61, w: 4.88, h: 1.63, d: 1.63 },
    { x: 22.17, y: -0.86, z: 5.45, w: 11.38, h: 0.81, d: 6.5 },
    { x: 22.17, y: -0.86, z: 9.11, w: 13, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: 28.27, y: -0.86, z: 5.45, w: 0.81, h: 0.81, d: 8.13 }, // approx (angled brush)
    { x: 24.2, y: -0.86, z: 1.79, w: 8.94, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: 16.08, y: -0.86, z: 5.86, w: 0.81, h: 0.81, d: 7.32 }, // approx (angled brush)
    { x: 26.24, y: -5.33, z: 5.45, w: 1.63, h: 8.13, d: 1.63 },
    { x: 18.11, y: -5.33, z: 5.45, w: 1.63, h: 8.13, d: 1.63 },
    { x: 15.26, y: 7.47, z: 6.27, w: 0.81, h: 1.22, d: 0.81 }, // approx (angled brush)
    { x: 15.26, y: 7.47, z: -6.33, w: 0.81, h: 1.22, d: 0.81 }, // approx (angled brush)
    { x: 8.96, y: 6.45, z: 6.27, w: 13.41, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: 8.96, y: 6.45, z: -0.03, w: 11.79, h: 0.81, d: 11.79 },
    { x: 15.26, y: 6.45, z: -0.03, w: 0.81, h: 0.81, d: 13.41 }, // approx (angled brush)
    { x: 10.39, y: 7.67, z: -4.3, w: 1.63, h: 1.63, d: 1.63 },
    { x: 8.35, y: 7.67, z: -5.52, w: 1.63, h: 1.63, d: 1.63 },
    { x: 8.96, y: 6.45, z: -6.33, w: 13.41, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: 2.66, y: 6.45, z: -5.32, w: 0.81, h: 0.81, d: 2.84 }, // approx (angled brush)
    { x: 2.66, y: 7.47, z: -6.33, w: 0.81, h: 1.22, d: 0.81 }, // approx (angled brush)
    { x: 3.88, y: 7.67, z: 3.42, w: 1.63, h: 1.63, d: 1.63 },
    { x: 2.66, y: 6.45, z: 5.25, w: 0.81, h: 0.81, d: 2.84 }, // approx (angled brush)
    { x: 2.66, y: 7.47, z: 6.27, w: 0.81, h: 1.22, d: 0.81 }, // approx (angled brush)
    { x: 0.23, y: 8.48, z: -3.29, w: 5.69, h: 3.25, d: 2.84 },
    { x: 0.23, y: 8.48, z: -0.24, w: 5.28, h: 3.25, d: 3.25 },
    { x: 0.23, y: 8.48, z: 3.01, w: 5.69, h: 3.25, d: 3.25 },
    { x: 0.23, y: 10.52, z: -0.24, w: 7.32, h: 0.81, d: 10.57 }, // approx (angled brush)
    { x: 0.23, y: 6.45, z: 4.23, w: 5.69, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: -2.21, y: 6.45, z: -0.03, w: 0.81, h: 0.81, d: 9.35 }, // approx (angled brush)
    { x: 0.63, y: 6.45, z: -0.03, w: 4.88, h: 0.81, d: 7.72 },
    { x: 0.63, y: -1.68, z: -0.24, w: 1.63, h: 15.44, d: 1.63 },
    { x: 0.23, y: 6.45, z: -4.3, w: 5.69, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: 8.76, y: -1.68, z: -0.24, w: 1.63, h: 15.44, d: 1.63 },
    { x: -2.42, y: 13.97, z: -4.1, w: 1.22, h: 6.1, d: 1.22 }, // approx (angled brush)
    { x: -2.42, y: 17.22, z: -4.1, w: 0.41, h: 0.41, d: 0.41 },
    { x: -6.48, y: 6.45, z: -0.24, w: 7.72, h: 0.81, d: 2.44 },
    { x: -6.48, y: 6.45, z: -1.86, w: 7.72, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: -6.48, y: 6.45, z: 1.39, w: 7.72, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: -9.93, y: 6.45, z: 3.22, w: 0.81, h: 0.81, d: 4.47 }, // approx (angled brush)
    { x: -19.79, y: 6.45, z: -0.24, w: 0.61, h: 0.81, d: 9.75 },
    { x: -19.28, y: 6.45, z: -4.81, w: 0.41, h: 0.81, d: 0.61 },
    { x: -19.28, y: 6.45, z: -0.24, w: 0.41, h: 0.81, d: 7.72 },
    { x: -19.28, y: 6.45, z: 4.33, w: 0.41, h: 0.81, d: 0.61 },
    { x: -15.22, y: 6.45, z: -0.24, w: 7.72, h: 0.81, d: 9.75 },
    { x: -10.65, y: 6.45, z: -0.24, w: 0.61, h: 0.81, d: 9.75 },
    { x: -11.15, y: 6.45, z: 4.33, w: 0.41, h: 0.81, d: 0.61 },
    { x: -11.15, y: 6.45, z: -4.81, w: 0.41, h: 0.81, d: 0.61 },
    { x: -11.15, y: 6.45, z: -0.24, w: 0.41, h: 0.81, d: 7.72 },
    { x: -9.93, y: 6.45, z: -3.69, w: 0.81, h: 0.81, d: 4.47 }, // approx (angled brush)
    { x: -15.22, y: 6.45, z: -5.52, w: 11.38, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: -20.5, y: 6.45, z: -0.24, w: 0.81, h: 0.81, d: 11.38 }, // approx (angled brush)
    { x: -15.22, y: 6.45, z: 5.05, w: 11.38, h: 0.81, d: 0.81 }, // approx (angled brush)
    { x: -15.22, y: -1.68, z: -0.03, w: 1.63, h: 15.44, d: 1.63 },
    { x: -11.15, y: 6.45, z: -4.3, w: 0.41, h: 0.81, d: 0.41 },
    { x: -11.15, y: 6.45, z: 3.83, w: 0.41, h: 0.81, d: 0.41 },
    { x: -19.28, y: 6.45, z: 3.83, w: 0.41, h: 0.81, d: 0.41 },
    { x: -19.28, y: 6.45, z: -4.3, w: 0.41, h: 0.81, d: 0.41 },
    { x: 17.7, y: -0.86, z: 1.79, w: 2.44, h: 0.81, d: 0.81 },
    { x: 37.31, y: -6.55, z: -13.75, w: 0.81, h: 0.81, d: 0.81 },
    { x: 37.31, y: -6.55, z: -13.75, w: 0.81, h: 0.81, d: 0.81 },
    { x: 37.31, y: -6.55, z: -13.75, w: 0.81, h: 0.81, d: 0.81 },
  ],
  spawnPoints: [
    { x: 5.92, y: 8.08, z: -4.71, yaw: -1.5708 },
    { x: -18.47, y: 7.06, z: -4.3, yaw: -1.5708 },
    { x: -11.97, y: 7.06, z: 3.62, yaw: 0.8901 },
    { x: 22.07, y: 0, z: 5.35, yaw: 1.5621 },
    { x: 13.84, y: 8.08, z: -4.71, yaw: 1.5708 },
    { x: 13.54, y: 8.08, z: 2.51, yaw: 1.5708 },
    { x: 5.61, y: 8.08, z: 2.51, yaw: -1.5708 },
    { x: -12.17, y: 7.06, z: -4, yaw: 2.2515 },
    { x: -18.37, y: 7.06, z: 3.73, yaw: -1.5708 },
  ],
  pickupSpots: [
    { x: 17.8, y: 33.58, z: -0.34 },
    { x: -6.38, y: 33.58, z: -0.24 },
    { x: -1.2, y: 33.58, z: 2.71 },
    { x: 18.01, y: 33.58, z: 5.45 },
    { x: -15.32, y: 33.99, z: 1.9 },
    { x: -15.42, y: 33.99, z: -1.76 },
    { x: 13.33, y: 33.99, z: 3.93 },
    { x: 5.92, y: 33.58, z: -3.18 },
    { x: 1.95, y: 33.58, z: -3.18 },
    { x: -17.76, y: 33.58, z: -0.03 },
    { x: 23.7, y: 33.99, z: 5.55 },
  ],
  killY: -3.40,
  // Palette derived from the map's own data: 4 x light "213 214 180"
  // and the mean texdata reflectivity of its 19 materials.
  theme: {
    platform: 0x746960,
    accent: 0xfeffd6,
    skyTop: 0x0a0d0d,
    skyBottom: 0x21302f,
    fog: 0x141f1e,
    sun: 0xfefeef,
  },
};
